http.connection.timeout=10000
http.socket.timeout=10000
kafka.wait.timeout.seconds=10
account.deposit.max=9999999999999999.99
account.deposit.min=0
account.deposit.belowZero=-1
default.string=Test_%s
